### ISSUE TITLE
Streaming Zed images both via Gstream AND to ROS2?

### ISSUE THREAD

**Issue by peredwardsson** [stereolabs/zed-gstreamer#33]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Zed provides both a wrapper for ROS2 and a Gstreamer app. I find both to be useful for different things. ROS2 for making a SLAM map with the depth data, and gst for viewing high quality compressed video stream. Is it possible to marry these two functions, since video compression in ROS2 is in a very strange place? Does Zed support it, and how would I go about it?

### Use-Case

This makes teleoperating while mapping much easier, which is very helpful.

**Comment by Myzhar** [comment]
Hi @peredwardsson 
I'm sorry, but this is not possible by using the ZED GStreamer Plugin and the ZED ROS2 Wrapper because they run in different processes and the camera resources cannot be shared by different processes.
What you can do is write your own ZED Node that performs your tasks and pushes data in a GStreamer pipeline.
You can use both the ZED GStreamer Plugin and the ZED ROS2 Wrapper source code as an example of how to mix both the features.
We have no plans to make such an advanced feature unless there is a high demand from other users of both packages.

**Comment by peredwardsson** [comment]
Roger, suspected as much. I will have a look, thanks for providing the source code for such adventures. :)
