### ISSUE TITLE
camera-resolution parameter doesn't seem to work

### ISSUE THREAD

**Issue by antonioarbues** [stereolabs/zed-gstreamer#58]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hi, I am trying to run the following pipeline with and without the parameter `camera-resolution`. If I omit it, the pipeline runs, otherwise it doesn't. Even setting the parameter to the default value of 6 makes the pipeline fail.

```
gst-launch-1.0 zedsrc stream-type=2 camera-resolution=6 camera-fps=30 ! queue ! videoconvert ! video/x-raw,format=NV12,width=1280,height=1440 ! nvh264enc bitrate=3000 zerolatency=true preset=low-latency-hp rc-mode=cbr-ld-hq ! queue ! appsink name=appsink sync=false async=false emit-signals=true
```

### Steps to Reproduce

Run the command in the terminal with and without camera-resolution parameter

### Expected Result

Should work with camera-resolution=6 and with omitting the parameter

### Actual Result

Doesn't run when camera-resolution is set

### ZED Camera model

ZED Mini

### Environment

```shell
OS: Ubuntu 22.04
CPU: intel i7
GPU: Nvidia quadro P1000
SDK version: 4.1
zed-gstreamer repo installation method: cloned and built manually from main branch
```

**Comment by Myzhar** [comment]
Hi @antonioarbues 
the problem is that you are not using the correct resolution in `videoconvert`.
If you change `camera-resolution` you must adapt the full pipeline:

`$ gst-launch-1.0 zedsrc stream-type=2 camera-resolution=6 camera-fps=30 ! queue ! videoconvert ! video/x-raw,format=NV12,width=672,height=752 ! nvh264enc bitrate=3000 zerolatency=true preset=low-latency-hp rc-mode=cbr-ld-hq ! queue ! appsink name=appsink sync=false async=false emit-signals=true`

**Comment by antonioarbues** [comment]
You're right, my bad.
In fact this works
```
gst-launch-1.0 zedsrc stream-type=2 camera-fps=30 camera-resolution=6 ! fakesink
```
